### ISSUE TITLE
Remove `.required(tip)`

### ISSUE THREAD

**Issue by danneu** [danneu/koa-bouncer#10]
I added `.required(tip)` when I added `.optional(tip)` since it seemed like a good idea at the time to have a mirror method.

`.optional(tip)` simply short-circuits a validation if the underlying key/val is `undefined` or empty string `""`.   (Even though it seems inconsistent, it made sense to short-circuit on empty string since an input left empty like `<input name="email">` will send an empty string.)

That means that `.required(tip)` simply ensures that the val is not `undefined`.

However I find `.required` to be useless and particularly unclear in practice. You end up using checks like `.isString` and `.toInt` anyways, in which case `.required` is superfluous. And I can't think of a case where you only want to check if a value is defined.

**Comment by onbjerg** [comment]
I think it's nice to be explicit about it in your code, so I don't think it's necessary to remove it.

**Comment by danneu** [comment]
I agree.
