### ISSUE TITLE
add `notEq`

### ISSUE THREAD

**Issue by varHarrie** [danneu/koa-bouncer#13]
add `notEq` to ensure `val !== otherVal`

BTW, is there any way to simplify that:
```javascript
// ensures `name` is a significative string, not empty and not  space characters
// '' ==> false
// '    ' ==> false
ctx.validateBody('name').isString().trim().notEq('')
```

**Comment by danneu** [comment]
@varHarrie Good idea.

I'm not sure how it could be shortened.

**Comment by varHarrie** [comment]
@danneu I mean we can add `notEmpty` to do that, and I think add custom validator for myself is a good choice.
