### ISSUE TITLE
Change default install to Koa 2.x version

### ISSUE THREAD

**Issue by lukeramsden** [danneu/koa-bouncer#15]
As Koa 2.x is now the standard, maybe the @next branch should become the standard?

**Comment by danneu** [comment]
Agreed, I need to update this.

**Comment by uniibu** [comment]
Hi its me again, can we atleast update this and make @next branch as the master. If not for the koa's warning i would have not known that ive forgotten the @next keyword when doing npm install on koa-bouncer.

**Comment by danneu** [comment]
Thanks for bumping this. I'll publish a new stable release this week. Sorry for the delay.

I'll also bump the two outdated deps.

**Comment by posquit0** [comment]
I want, too 👍

**Comment by danneu** [comment]
Sorry for the wait. Stable release was bumped to the `6.x` major version and now supports koa2 by default.

I don't have time to update the readme now though, so the readme still demonstrates koa1 middleware and `this` instead of `ctx`.
