### ISSUE TITLE
Koa 2.0

### ISSUE THREAD

**Issue by onbjerg** [danneu/koa-bouncer#8]
Does this work with Koa 2?

**Comment by danneu** [comment]
@onbjerg No. I happen to only be working on Koa 1 projects. It's definitely a TODO and involves basically changing all the `this` to `ctx` afaict.

**Comment by onbjerg** [comment]
@danneu Sort of. There's no generator functions in Koa 2 either.

Is this something you would be interested in having as a @2 or @next tag?

**Comment by danneu** [comment]
Thanks again. https://github.com/danneu/koa-bouncer/tree/next

**Comment by varHarrie** [comment]
How to install for Koa v2? `koa-bouncer@next` or `koa-bouncer@2`?

**Comment by danneu** [comment]
@varHarrie it's `koa-bouncer@next`. Sorry, need to document it better.

I look forward to the ecosystem advancing past the koa 1 vs 2 limbo.
